### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by athariqk** [clayjohn/Godot_Atmosphere_Demo#1]
Hey, so I was wondering what's the permissibility of this demo. Is it safe to be used and modified (or at least take some part of it) in our Godot project? I'm assuming it is and it'd be awesome but just to make sure. Thanks!

**Comment by clayjohn** [comment]
I wasn't sure of the licence when I ported the code, which is why I left it blank. However, using the wayback machine to find the original website, it looks like Sean released the code under the BSD Licence: https://web.archive.org/web/20090131015809/http://sponeil.net/downloads.htm

I can update this repo to include that as well as my own licence (MIT) for the godot-specific portions of the project. 

In either case you are free to use everything in your own project :)
